name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump version
      id: bump_version
      run: echo "::set-output name=VERSION::$(make version)"

    - name: Build everything
      run: make all

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{ needs.build.outputs.VERSION }}
        draft: false
        prerelease: false
        title: Release v${{ needs.build.outputs.VERSION }}
        files: |
          bin/*
          *.tar.gz
