name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version
      id: version
      run: echo "VERSION=$(make version)" >> $GITHUB_OUTPUT

    - name: Build everything
      run: make all

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        title: Release v${{ steps.get_version.outputs.VERSION }}
        files: |
          bin/*
          *.tar.gz
